# Generated by Django 5.1.6 on 2026-03-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_tasks', '0002_taskprofile'),
        ('bitrix_tasks', '0004_remove_taskprofile'),
    ]

    operations = [
    ]
