# Generated by Django 5.1.6 on 2026-03-02 12:49

import bitrix_tasks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_tasks', '0007_bitrix24task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segmentationresult',
            options={'verbose_name': 'Результат сегментации (запуск)', 'verbose_name_plural': 'Результаты сегментации (запуск)'},
        ),
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Транскрипция', 'verbose_name_plural': 'Транскрипции'},
        ),
        migrations.AddField(
            model_name='bitrix24task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitrix24_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='bitrixconnection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_connections', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_runs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='taskconfig',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_configs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='bitrix24task',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Запуск каждые N минут (для Celery Beat).', verbose_name='Интервал (минут)'),
        ),
        migrations.AlterField(
            model_name='run',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='bitrix_tasks.taskconfig'),
        ),
        migrations.AlterField(
            model_name='segmentationresult',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation_result', to='bitrix_tasks.run'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Оставьте пустым — записи берутся через API телефонии (voximplant.statistic.get), как в sa. Либо укажите путь по диску: Телефония - записи звонков / 2025-03', max_length=500, verbose_name='Путь к папке (названия через /)'),
        ),
        migrations.AlterField(
            model_name='taskconfig',
            name='vosk_model_path',
            field=models.CharField(default=bitrix_tasks.models._default_vosk_model_path, help_text='По умолчанию: папка vosk-model-ru-0.42 в корне проекта.', max_length=500, verbose_name='Путь к модели Vosk'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='bitrix_tasks.bitrixconnection'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='bitrix_tasks.run'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('LEAD', 'Лид'), ('CONTACT', 'Контакт'), ('DEAL', 'Сделка'), ('CALL', 'Звонок')], default='CALL', max_length=20, verbose_name='Тип сущности')),
                ('entity_id', models.CharField(db_index=True, max_length=100, verbose_name='ID в Битрикс')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='bitrix_tasks.bitrixconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контакт (сущность CRM)',
                'verbose_name_plural': 'Контакты (сущности CRM)',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'connection', 'entity_type', 'entity_id')},
            },
        ),
        migrations.AddField(
            model_name='transcription',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='bitrix_tasks.contact', verbose_name='Контакт'),
        ),
        migrations.AlterUniqueTogether(
            name='transcription',
            unique_together={('contact', 'file_name')},
        ),
        migrations.CreateModel(
            name='ContactSegmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(default=list, help_text='Список тегов из DeepSeek', verbose_name='Теги')),
                ('raw_response', models.TextField(blank=True, verbose_name='Ответ DeepSeek (JSON)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segmentation', to='bitrix_tasks.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_segmentations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сегментация контакта',
                'verbose_name_plural': 'Сегментации контактов',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_recordings_allowed', models.PositiveIntegerField(blank=True, help_text='Макс. записей в одном запуске. Пусто — без ограничения.', null=True, verbose_name='Лимит записей на запуск')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
