# Generated by Django 5.1.6 on 2026-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_tasks', '0008_user_contacts_segmentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='progress_current',
            field=models.PositiveIntegerField(default=0, verbose_name='Обработано записей'),
        ),
        migrations.AddField(
            model_name='run',
            name='progress_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего записей в запуске'),
        ),
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(default='pending', help_text='pending / running / done / error', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='segmentationresult',
            name='summary',
            field=models.TextField(blank=True, help_text='Краткое текстовое саммари всех звонков запуска', verbose_name='Саммари по запуску'),
        ),
        migrations.AddField(
            model_name='transcription',
            name='brief',
            field=models.TextField(blank=True, help_text='Короткое описание звонка от DeepSeek', verbose_name='Краткая характеристика звонка'),
        ),
        migrations.AlterField(
            model_name='bitrix24task',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Не используется: задания запускаются только вручную.', verbose_name='Интервал (минут)'),
        ),
        migrations.AlterField(
            model_name='segmentationresult',
            name='text',
            field=models.TextField(verbose_name='Текст результата (JSON с тегами)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_recordings_allowed',
            field=models.PositiveIntegerField(blank=True, help_text='Общий лимит обработанных записей для пользователя. Пусто — без ограничения.', null=True, verbose_name='Всего разрешено записей'),
        ),
    ]
