# Generated by Django 5.1.6 on 2026-03-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_tasks', '0009_run_progress_current_run_progress_total_run_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrix24task',
            name='skip_existing',
            field=models.BooleanField(default=True, help_text='Если выключено — уже существующие транскрипции будут пересчитаны заново.', verbose_name='Пропускать уже транскрибированные записи'),
        ),
    ]
