# Generated by Django 5.1.6 on 2026-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix_tasks', '0010_bitrix24task_skip_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsegmentation',
            name='crm_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Агрегированные данные из лидов и сделок (стадии, суммы, источники и т.п.).', verbose_name='CRM-срез по контакту'),
        ),
    ]
